# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI integration with Maven

on:
  push:
      branches:  
      - main
      - jenk
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: jenk
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: SoftTest show Version
      run: "java -version"
    - name: SoftTest build
      run: mvn -B package --file pom.xml
    - name: Show dir
      run: 'pwd'
    - name: LS
      run: 'ls -al'
    - name: Dependencies
      run: 'mvn compile'
    - name: Build app
      run: 'mvn package -DskipTests'
    - name: Test app
      run: 'mvn test'
